# Generated by Django 5.1.7 on 2025-03-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('inventory', '0005_consumption_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('work_order_type', models.CharField(choices=[('PM01', 'Failure Work-Order'), ('PM02', 'Inspection Based Work-Order'), ('PM03', 'Scheduled Work-Order'), ('PM04', 'Project Work-Order')], max_length=30)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_order.activitytype')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_time_required', models.DurationField()),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='asset.equipment')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_orders', to='asset.machine')),
                ('materials_required', models.ManyToManyField(blank=True, related_name='material_work_orders', to='inventory.item')),
                ('tools_required', models.ManyToManyField(blank=True, related_name='tool_work_orders', to='inventory.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=250)),
                ('value', models.BooleanField(choices=[(True, 'Yes'), (False, 'No'), (None, '-')], default=None)),
                ('remark', models.TextField(max_length=250)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='work_order.activity')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.workorder')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
