# Generated by Django 5.1.7 on 2025-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_remove_workorderactivity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Created', 'Created'), ('Assigned', 'Assigned'), ('Incomplete', 'Incomplete'), ('Completed', 'Completed')], default='Created', max_length=25),
        ),
    ]
