# Generated by Django 5.1.7 on 2025-04-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_workordertype_alter_workorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='work_order.workordertype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='work_order.activitytype'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='work_order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='work_order.workordertype'),
        ),
    ]
