# Generated by Django 5.1.7 on 2025-04-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_workorder_work_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='work_order.activitytype'),
        ),
    ]
