# Generated by Django 5.1.7 on 2025-04-16 08:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0006_workorder_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['code'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='workorderactivity',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name_plural': 'Work Order Activities'},
        ),
        migrations.AddField(
            model_name='workorder',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='workorderactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_order_activities', to='work_order.activity'),
        ),
        migrations.AlterField(
            model_name='workorderactivity',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_activities', to='work_order.workorder'),
        ),
    ]
