# Generated by Django 5.1.7 on 2025-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_consumption_reason_return_reason_return_used'),
        ('work_order', '0007_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='materials_required',
        ),
        migrations.AddField(
            model_name='workorder',
            name='spareparts_required',
            field=models.ManyToManyField(blank=True, related_name='sparepart_work_orders', to='inventory.item'),
        ),
    ]
