# Generated by Django 5.1.7 on 2025-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0008_remove_workorder_materials_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderactivity',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No'), (None, '-')], null=True),
        ),
    ]
