# Generated by Django 5.1.7 on 2025-04-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('work_order', '0010_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='work_orders', to='schedule.schedule'),
        ),
    ]
