# Generated by Django 5.1.7 on 2025-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0011_workorder_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertype',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
