# Generated by Django 5.1.7 on 2025-04-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_alter_breakdown_end_date'),
        ('work_order', '0013_workorder_assigned_users_workorder_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='breakdown',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='work_orders', to='breakdown.breakdown'),
        ),
    ]
