# Generated by Django 5.1.7 on 2025-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0014_workorder_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
