# Generated by Django 5.1.7 on 2025-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0016_rename_date_workorder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertype',
            name='breakdown',
            field=models.BooleanField(default=False),
        ),
    ]
