# Generated by Django 5.1.7 on 2025-04-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_alter_breakdown_end_date'),
        ('work_order', '0017_workordertype_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='remark',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='breakdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='work_orders', to='breakdown.breakdown'),
        ),
    ]
