# Generated by Django 5.1.7 on 2025-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0018_workorder_remark_alter_workorder_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderactivity',
            name='value',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
