# Generated by Django 5.1.7 on 2025-04-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0019_alter_workorderactivity_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workorderactivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Work Order Activities'},
        ),
    ]
