# Generated by Django 5.1.7 on 2025-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0020_alter_workorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='total_time_required',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
