# Generated by Django 5.1.7 on 2025-05-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0021_alter_workorder_total_time_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderactivity',
            name='description',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorderactivity',
            name='activity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
