# Generated by Django 5.1.7 on 2025-05-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0022_workorderactivity_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderactivity',
            options={'ordering': ['description', '-created_at', '-updated_at'], 'verbose_name_plural': 'Work Order Activities'},
        ),
    ]
