# Generated by Django 5.1.7 on 2025-05-27 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0023_alter_workorderactivity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
