# Generated by Django 5.1.7 on 2025-06-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_schedule_planned_time"),
        ("work_order", "0024_alter_workorder_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["description"], "verbose_name_plural": "Activities"},
        ),
        migrations.RemoveField(
            model_name="activity",
            name="activity_type",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="code",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="name",
        ),
        migrations.RemoveField(
            model_name="workorderactivity",
            name="activity",
        ),
        migrations.AddField(
            model_name="activity",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="schedule.schedule",
            ),
        ),
    ]
