# Generated by Django 5.1.7 on 2025-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "work_order",
            "0025_alter_activity_options_remove_activity_activity_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
