# Generated by Django 5.1.7 on 2025-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0026_activity_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderactivity',
            name='remark',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
