# Generated by Django 5.1.7 on 2025-07-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_order", "0027_alter_workorderactivity_remark"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorderactivity",
            options={
                "ordering": ["created_at", "updated_at", "description"],
                "verbose_name_plural": "Work Order Activities",
            },
        ),
    ]
