# Generated by Django 5.1.7 on 2025-08-08 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order", "0028_alter_workorderactivity_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(max_length=250)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["created_at", "description"],
            },
        ),
        migrations.AlterModelOptions(
            name="workorderactivity",
            options={
                "ordering": ["created_at", "description"],
                "verbose_name_plural": "Work Order Activities",
            },
        ),
        migrations.AddField(
            model_name="workorder",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="checked_work_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Requested", "Requested"),
                    ("Accepted", "Accepted"),
                    ("Created", "Created"),
                    ("Assigned", "Assigned"),
                    ("Checked", "Checked"),
                    ("Incomplete", "Incomplete"),
                    ("Completed", "Completed"),
                ],
                default="Created",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(max_length=250)),
                (
                    "value",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                ("remark", models.TextField(blank=True, max_length=250, null=True)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_clearances",
                        to="work_order.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "description"],
            },
        ),
    ]
