# Generated by Django 5.1.7 on 2025-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order", "0029_clearance_alter_workorderactivity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clearance",
            name="type",
            field=models.CharField(
                choices=[
                    ("Breakdown", "Breakdown"),
                    ("Scheduled", "Scheduled"),
                    ("None", "None"),
                ],
                default="None",
            ),
        ),
    ]
