# Generated by Django 5.1.7 on 2025-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order", "0030_clearance_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clearance",
            name="type",
        ),
        migrations.AddField(
            model_name="clearance",
            name="breakdown",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clearance",
            name="scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
