# Generated by Django 5.1.7 on 2025-04-10 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0014_consumption_reason_return_reason_return_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=20)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_approvals', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_approvals', to='inventory.purchaserequest')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
