# Generated by Django 5.1.7 on 2025-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='remark',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
