# Generated by Django 5.1.7 on 2025-04-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_purchase_remark'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_approvals', to='purchase.request'),
        ),
    ]
