# Generated by Django 5.1.7 on 2025-05-06 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='location',
        ),
        migrations.AddField(
            model_name='machine',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='machines', to='location.area'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
