# Generated by Django 5.1.7 on 2025-07-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_remove_machine_location_machine_area_delete_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AlterField(
            model_name="machine",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="machines",
                to="asset.area",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="areas",
                to="asset.plant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="area",
            unique_together={("code", "plant")},
        ),
    ]
