# Generated by Django 5.1.7 on 2025-07-24 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_area_plant_alter_machine_area_area_plant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="plant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas",
                to="asset.plant",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="machine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipments",
                to="asset.machine",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines",
                to="asset.area",
            ),
        ),
    ]
