# Generated by Django 5.1.7 on 2025-04-28 09:11

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0017_remove_purchaserequest_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requested_date', models.DateField(default=datetime.date.today)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('URGENT', 'URGENT'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=25)),
                ('status', models.CharField(choices=[('PENDING-APPROVAL', 'PENDING-APPROVAL'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('RECEIVED', 'RECEIVED')], default='PENDING-APPROVAL', max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_requests', to='inventory.item')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2026)])),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_schedule', to='inventory.item')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('january', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('february', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('march', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('april', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('june', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('july', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('august', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('september', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('october', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('november', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('december', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='monthly_schedule', to='purchase.schedule')),
            ],
            options={
                'ordering': ['schedule__year'],
            },
        ),
    ]
