# Generated by Django 5.1.7 on 2025-04-28 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_item_minimum_stock_level'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_schedule', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
