# Generated by Django 5.1.7 on 2025-05-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_year_alter_schedule_options_remove_schedule_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
