# Generated by Django 5.1.7 on 2025-05-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_transfer_options_alter_transferitem_options_and_more'),
        ('purchase', '0006_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.location'),
        ),
    ]
