# Generated by Django 5.1.7 on 2025-07-28 13:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_alter_inventory_item"),
        ("purchase", "0007_request_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="received_date",
            new_name="approved_date",
        ),
        migrations.RemoveField(
            model_name="request",
            name="item",
        ),
        migrations.RemoveField(
            model_name="request",
            name="location",
        ),
        migrations.RemoveField(
            model_name="request",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="request",
            name="received_quantity",
        ),
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchase_histories",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchase_histories",
                        to="inventory.location",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_histories",
                        to="purchase.request",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "purchase histories",
                "ordering": ["-created_at", "request__id", "item__name"],
            },
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchase_requests",
                        to="inventory.item",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_items",
                        to="purchase.request",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
