# Generated by Django 5.1.7 on 2025-07-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_alter_inventory_item"),
        ("purchase", "0008_rename_received_date_request_approved_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="purchase_requests",
                to="inventory.location",
            ),
            preserve_default=False,
        ),
    ]
