# Generated by Django 5.1.7 on 2025-07-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_remove_inventory_inbound_transfers_and_more"),
        ("purchase", "0009_request_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="request_items",
                to="inventory.item",
            ),
        ),
    ]
