# Generated by Django 5.1.7 on 2025-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_suppliers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='monthlypurchaseschedule',
            options={'ordering': ['month']},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseschedule',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='monthlypurchaseschedule',
            name='month',
            field=models.CharField(choices=[(1, 'JANUARY'), (2, 'FEBRUARY'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUGUST'), (9, 'SEPTEMBER'), (10, 'OCTOBER'), (11, 'NOVEMBER'), (12, 'DECEMBER')], default=1, max_length=25),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
