# Generated by Django 5.1.7 on 2025-04-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('inventory', '0015_consumption_date_return_date'),
        ('work_order', '0010_activity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('planned_time', models.DurationField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='work_order.activitytype')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='asset.equipment')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='asset.machine')),
                ('spareparts_required', models.ManyToManyField(blank=True, related_name='sparepart_schedules', to='inventory.item')),
                ('tools_required', models.ManyToManyField(blank=True, related_name='tool_schedules', to='inventory.item')),
                ('work_order_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='work_order.workordertype')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
