# Generated by Django 5.1.7 on 2025-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='planned_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
