# Generated by Django 5.1.7 on 2025-07-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_area_plant_alter_machine_area_area_plant_and_more"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Area",
        ),
        migrations.DeleteModel(
            name="Plant",
        ),
    ]
