# Generated by Django 5.1.7 on 2025-03-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_contact_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'inventories'},
        ),
        migrations.AddField(
            model_name='item',
            name='no',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
