# Generated by Django 5.1.7 on 2025-04-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_consumption_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
