# Generated by Django 5.1.7 on 2025-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
