# Generated by Django 5.1.7 on 2025-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
