# Generated by Django 5.1.7 on 2025-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_consumed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypurchaseschedule',
            name='month',
            field=models.IntegerField(choices=[(1, 'JANUARY'), (2, 'FEBRUARY'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUGUST'), (9, 'SEPTEMBER'), (10, 'OCTOBER'), (11, 'NOVEMBER'), (12, 'DECEMBER')], default=1),
        ),
    ]
