# Generated by Django 5.1.7 on 2025-04-10 05:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_purchaserequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
