# Generated by Django 5.1.7 on 2025-04-10 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory', to='inventory.item'),
        ),
    ]
