# Generated by Django 5.1.7 on 2025-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='reason',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
