# Generated by Django 5.1.7 on 2025-04-17 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_consumption_reason_return_reason_return_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='return',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
