# Generated by Django 5.1.7 on 2025-04-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_consumption_date_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='location',
            new_name='address',
        ),
    ]
