# Generated by Django 5.1.7 on 2025-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rename_location_contact_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='purchaseschedule',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='MonthlyPurchaseSchedule',
        ),
    ]
