# Generated by Django 5.1.7 on 2025-04-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_alter_purchase_purchase_request'),
        ('inventory', '0017_remove_purchaserequest_approved_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
        migrations.DeleteModel(
            name='PurchaseSchedule',
        ),
    ]
