# Generated by Django 5.1.7 on 2025-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_delete_purchaserequest_delete_purchaseschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='minimum_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
