# Generated by Django 5.1.7 on 2025-05-20 09:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_alter_item_minimum_stock_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ShelfBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="consumed_quantity",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="purchased_quantity",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="returned_quantity",
        ),
        migrations.AddField(
            model_name="inventory",
            name="inbound_transfers",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="outbound_transfers",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="purchased",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="location",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inventories",
                to="inventory.location",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shelves",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="shelf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="items",
                to="inventory.shelf",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="items",
                to="inventory.shelfbox",
            ),
        ),
        migrations.CreateModel(
            name="ShelfRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rows",
                        to="inventory.shelf",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="shelfbox",
            name="row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="boxes",
                to="inventory.shelfrow",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="row",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="items",
                to="inventory.shelfrow",
            ),
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING-APPROVAL", "PENDING-APPROVAL"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("SHIPPED", "SHIPPED"),
                            ("RECEIVED", "RECEIVED"),
                        ],
                        default="PENDING-APPROVAL",
                        max_length=25,
                    ),
                ),
                ("requested_date", models.DateField(default=datetime.datetime.now)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("shipment_date", models.DateField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_from",
                        to="inventory.location",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_to",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transfered_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfer_items",
                        to="inventory.item",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_items",
                        to="inventory.transfer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
