# Generated by Django 5.1.7 on 2025-05-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_location_shelfbox_remove_inventory_consumed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='inventories', to='inventory.location'),
            preserve_default=False,
        ),
    ]
