# Generated by Django 5.1.7 on 2025-05-23 10:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_inventory_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-requested_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transferitem',
            options={'ordering': ['-item__name', 'created_at']},
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('INBOUND', 'INBOUND'), ('OUTBOUND', 'OUTBOUND')], max_length=25, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_histories', to='inventory.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_histories', to='inventory.location')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_histories', to='inventory.transfer')),
            ],
            options={
                'ordering': ['-created_at', 'transfer__id', 'item__name', 'type'],
            },
        ),
    ]
