# Generated by Django 5.1.7 on 2025-05-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_transfer_options_alter_transferitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory', to='inventory.item'),
        ),
    ]
