# Generated by Django 5.1.7 on 2025-05-27 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_transfer_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='return',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='requested_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
