# Generated by Django 5.1.7 on 2025-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_consumption_date_alter_return_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['code'], 'verbose_name_plural': 'shelves'},
        ),
        migrations.AlterModelOptions(
            name='shelfbox',
            options={'ordering': ['code'], 'verbose_name_plural': 'shelf boxes'},
        ),
        migrations.AlterModelOptions(
            name='transferhistory',
            options={'ordering': ['-created_at', 'transfer__id', 'item__name', 'type'], 'verbose_name_plural': 'transfer histories'},
        ),
        migrations.RenameField(
            model_name='transferitem',
            old_name='transfered_quantity',
            new_name='received_quantity',
        ),
        migrations.AddField(
            model_name='transferitem',
            name='shipped_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
