# Generated by Django 5.1.7 on 2025-05-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_shelf_options_alter_shelfbox_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferitem',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='shipped_quantity',
        ),
    ]
