# Generated by Django 5.1.7 on 2025-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_transferitem_received_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
