# Generated by Django 5.1.7 on 2025-06-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_alter_inventory_options_alter_item_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["name", "-created_at"]},
        ),
    ]
