# Generated by Django 5.1.7 on 2025-07-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_alter_item_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "ordering": ["-item__created_at", "location__code"],
                "verbose_name_plural": "inventories",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at"]},
        ),
    ]
