# Generated by Django 5.1.7 on 2025-07-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_alter_inventory_options_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="inventory.item",
            ),
        ),
    ]
