# Generated by Django 5.1.7 on 2025-07-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_alter_inventory_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="inbound_transfers",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="outbound_transfers",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="purchased",
        ),
    ]
