# Generated by Django 5.1.7 on 2025-07-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_remove_inventory_inbound_transfers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="balance",
        ),
    ]
