# Generated by Django 5.1.7 on 2025-04-22 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdown',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='breakdown',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='breakdown',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
