# Generated by Django 5.1.7 on 2025-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0002_alter_breakdown_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
