# Generated by Django 5.1.7 on 2025-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown', '0003_alter_breakdown_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='remark',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('WORK-ORDER CREATED', 'WORK-ORDER CREATED'), ('WORK-ORDER COMPLETED', 'WORK-ORDER COMPLETED'), ('FIXED', 'FIXED')], default='CREATED', max_length=20),
        ),
    ]
